qgis-app/styles/urls.py
from django.urls import path
from styles.views import (
    StyleByTypeListView,
    StyleCreateView,
    StyleDeleteView,
    StyleDetailView,
    StyleDownloadView,
    StyleListView,
    StyleRequireActionListView,
    StyleReviewView,
    StyleUnapprovedListView,
    StyleUpdateView,
    StyleByTagView,
    style_nav_content,
    style_type_list,
)

urlpatterns = [
    path("", StyleListView.as_view(), name="style_list"),
    path("add/", StyleCreateView.as_view(), name="style_create"),
    path("<int:pk>/", StyleDetailView.as_view(), name="style_detail"),
    path("<int:pk>/download/", StyleDownloadView.as_view(), name="style_download"),
    path("<int:pk>/delete/", StyleDeleteView.as_view(), name="style_delete"),
    path("<int:pk>/update/", StyleUpdateView.as_view(), name="style_update"),
    path("unapproved/", StyleUnapprovedListView.as_view(), name="style_unapproved"),
    path(
        "require_action/",
        StyleRequireActionListView.as_view(),
        name="style_require_action",
    ),
    path("types/<style_type>/", StyleByTypeListView.as_view(), name="style_by_type"),
    path("<int:pk>/review/", StyleReviewView.as_view(), name="style_review"),
    path("tags/<style_tag>/", StyleByTagView.as_view(), name="style_tag"),
    # JSON
    path("sidebarnav/", style_nav_content, name="style_nav_content"),
    path("sidebarnav_type/", style_type_list, name="style_nav_typelist"),
]

qgis-app/urls.py
import simplemenu
from django.conf import settings
from django.urls import re_path as url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.flatpages.models import FlatPage
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.views.static import serve
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

# to find users app views
# from users.views import *
from homepage import homepage
from rest_framework import permissions
from docs import docs_publish

admin.autodiscover()


schema_view = get_schema_view(
    openapi.Info(
        title="Hub API",
        default_version="v1",
        description="Hub API for sharing files application",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="email@example.com"),
        license=openapi.License(name="CC"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # Example:
    # (r'^qgis/', include('qgis.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r"^admin/", admin.site.urls),
    # ABP: plugins app
    url(r"^plugins/", include("plugins.urls")),
    # (r'^tags/', include('cab.urls.tags')),
    # (r'^bookmarks/', include('cab.urls.bookmarks')),
    # (r'^languages/', include('cab.urls.languages')),
    # (r'^popular/', include('cab.urls.popular')),
    url(r"^search/", include("custom_haystack_urls")),
    url(r"^search/", include("haystack.urls")),
    # AG: User Map
    # url(r'^community-map/', include('user_map.urls', namespace='user_map')),
    # Fix broken URLS in feedjack
    # url(r'^planet/feed/$', RedirectView.as_view(url='/planet/feed/atom/')),
    # Tim: Feedjack feed aggregator / planet
    url(r"^planet/", include("feedjack.urls")),
    # ABP: autosuggest for tags
    url(r"^taggit_autosuggest/", include("taggit_autosuggest.urls")),
    url(r"^userexport/", include("userexport.urls")),
    # Styles and other files sharing
    url(r"^styles/", include("styles.urls")),
    url(r"^geopackages/", include("geopackages.urls")),
    url(r"^layerdefinitions/", include("layerdefinitions.urls")),
    url(r"^models/", include("models.urls")),
    url(r"^wavefronts/", include("wavefronts.urls")),
]

# ABP: temporary home page
# urlpatterns += patterns('django.views.generic.simple',
#    url(r'^$', 'direct_to_template', {'template': 'index.html'}, name = 'index'),
# )


# serving static media
from django.conf.urls.static import static

if settings.SERVE_STATIC_MEDIA:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# auth
urlpatterns += [
    path("accounts/", include("django.contrib.auth.urls")),
]

# tinymce
urlpatterns += [
    url(r"^tinymce/", include("tinymce.urls")),
]


# Home
urlpatterns += [
    url(r"^$", homepage),
    url(r"^publish", docs_publish, name="docs_publish"),
]

# API
urlpatterns += [
    url(r"^api/v1/", include("api.urls")),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r"^__debug__/", include(debug_toolbar.urls)),
    ]

simplemenu.register(
    "/admin/",
    "/planet/",
    #    '/community-map/',
    "/plugins/",
    "/styles/?order_by=-upload_date&&is_gallery=true",
    "/geopackages/?order_by=-upload_date&&is_gallery=true",
    "/layerdefinitions/?order_by=-upload_date&&is_gallery=true",
    "/models/?order_by=-upload_date&&is_gallery=true",
    "/wavefronts/?order_by=-upload_date&&is_gallery=true",
    FlatPage.objects.exclude(url="/publish/"),
    simplemenu.models.URLItem.objects.all(),
)

qgis-app/styles/models.py
from base.models.processing_models import Resource, ResourceReview
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

STYLES_STORAGE_PATH = getattr(settings, "PLUGINS_STORAGE_PATH", "styles/%Y")


class StyleType(models.Model):
    """
    Style Type model
    """

    # symbol, name and desc
    # symbol_type e.g. "line"
    # name e.g. "Line"
    symbol_type = models.CharField(
        _("Symbol type"),
        help_text=_(
            "This will be used to identify the type of a style. "
            "The value will be extracted automatically from "
            "the uploaded QGIS style XML file."
        ),
        max_length=256,
        unique=True,
    )
    name = models.CharField(
        _("Name"),
        help_text=_(
            "Default to the title case string of symbol_type. "
            "e.g. line would become Line."
        ),
        max_length=256,
        unique=True,
    )
    description = models.TextField(
        _("Description"),
        help_text=_("A short description of this style type."),
        max_length=1000,
        blank=True,
        null=True,
    )

    # icon image
    icon = models.ImageField(
        _("Icon"),
        help_text=_("Please ensure the icon file is 500x500 px " "and in PNG format."),
        upload_to=STYLES_STORAGE_PATH,
        blank=True,
        null=True,
    )

    # Ordering for StyleType instance
    order = models.IntegerField(
        _("Order"), help_text=_("Order value for custom ordering."), default=0
    )

    class Meta:
        ordering = ("order",)

    def __unicode__(self):
        return "%s" % (self.name)

    def __str__(self):
        return self.__unicode__()


class Style(Resource):
    """
    Style Model.

    A style is an XML document exported from the QGIS Style manager.
    """

    # style type
    style_type = models.ForeignKey(
        StyleType,
        verbose_name=_("Type"),
        help_text=_(
            "The type of this style, this will automatically be read "
            "from the XML file."
        ),
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        db_index=True,
    )

    # name and desc
    name = models.CharField(
        _("Name"),
        help_text=_(
            "A unique name for this style. This will be initially "
            "automatically taken from the uploaded XML file, but may "
            "need manual revision if the name is not unique."
        ),
        max_length=256,
        unique=True,
    )
    description = models.TextField(
        _("Description"), help_text=_("A description of this style."), max_length=5000
    )

    # thumbnail
    thumbnail_image = models.ImageField(
        _("Thumbnail"),
        help_text=_(
            "Please upload an image that represents this style. "
            "The image should be square when uploaded."
        ),
        blank=True,
        null=True,
        upload_to=STYLES_STORAGE_PATH,
    )

    # file
    file = models.FileField(
        _("Style file"),
        help_text=_("A QGIS style file in XML format."),
        upload_to=STYLES_STORAGE_PATH,
        validators=[FileExtensionValidator(allowed_extensions=["xml"])],
        null=False,
    )

    def get_absolute_url(self):
        return reverse("style_detail", args=(self.id,))

    @property
    def get_style_type(self):
        return self.style_type.name


class Review(ResourceReview):

    # style
    resource = models.ForeignKey(
        Style,
        verbose_name=_("Style"),
        help_text=_("The reviewed Style."),
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )

qgis-app/styles/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from styles.file_handler import validator
from styles.models import Style
from taggit.forms import TagField

class ResourceFormMixin(forms.ModelForm):
    tags = TagField(required=False)
    class Meta:
        model = Style
        fields = [
            "file",
            "thumbnail_image",
            "name",
            "description",
            "tags"
        ]


class UploadForm(forms.ModelForm):
    """
    Style Upload Form.
    """

    tags = TagField(required=False)
    class Meta:
        model = Style
        fields = [
            "file",
            "thumbnail_image",
            "description",
            "tags"
        ]

    def clean_file(self):
        """
        Cleaning file field data.
        """

        xml_file = self.cleaned_data["file"]

        if xml_file:
            style = validator(xml_file.file)
            if not style:
                raise ValidationError(
                    _("Undefined style type. " "Please register your style type.")
                )
        return xml_file


class UpdateForm(ResourceFormMixin):
    """Style Update Form."""


class StyleReviewForm(forms.Form):
    """
    Style Review Form.
    """

    CHOICES = [("approve", "Approve"), ("reject", "Reject")]
    approval = forms.ChoiceField(
        required=True, choices=CHOICES, widget=forms.RadioSelect, initial="approve"
    )
    comment = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "placeholder": "Please provide clear feedback "
                "if you decided to not approve this style.",
                "rows": "5",
            }
        )
    )


class StyleSearchForm(forms.Form):
    """
    Search Form
    """

    q = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={"class": "search-query", "placeholder": "Search"}
        ),
    )

qgis-app/styles/views.py
import json

from base.views.processing_view import (
    ResourceBaseCreateView,
    ResourceBaseDeleteView,
    ResourceBaseDetailView,
    ResourceBaseDownload,
    ResourceBaseListView,
    ResourceBaseRequireActionListView,
    ResourceBaseReviewView,
    ResourceBaseUnapprovedListView,
    ResourceBaseUpdateView,
    resource_nav_content,
    resource_notify,
)
from django.conf import settings
from django.contrib import messages
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.crypto import get_random_string
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from styles.file_handler import read_xml_style
from styles.forms import UpdateForm, UploadForm
from styles.models import Review, Style, StyleType
from urllib.parse import unquote


class ResourceMixin:
    """Mixin class for Geopackage."""

    model = Style

    review_model = Review

    # The resource_name will be displayed as the app name on web page
    resource_name = "Style"

    # The url name in urls.py should start start with this value
    resource_name_url_base = "style"


class StyleCreateView(ResourceMixin, ResourceBaseCreateView):
    """
    Create a new style
    """

    form_class = UploadForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.creator = self.request.user
        xml_parse = read_xml_style(obj.file)
        if xml_parse:
            # check if name exists
            name_exist = Style.objects.filter(name__iexact=xml_parse["name"]).exists()
            if name_exist:
                obj.name = "%s_%s" % (
                    xml_parse["name"].title(),
                    get_random_string(length=5),
                )
            else:
                obj.name = xml_parse["name"].title()
            style_type = StyleType.objects.filter(symbol_type=xml_parse["type"]).first()
            if not style_type:
                style_type = StyleType.objects.create(
                    symbol_type=xml_parse["type"],
                    name=xml_parse["type"].title(),
                    description="Automatically created from '"
                    "'an uploaded Style file",
                )
            obj.style_type = style_type
        obj.save()
        # Without this next line the tags won't be saved.
        form.save_m2m()
        resource_notify(obj, self.resource_name)
        msg = _("The Style has been successfully created.")
        messages.success(self.request, msg, "success", fail_silently=True)
        return HttpResponseRedirect(reverse("style_detail", kwargs={"pk": obj.id}))


class StyleDetailView(ResourceMixin, ResourceBaseDetailView):
    """Style Detail View"""


class StyleUpdateView(ResourceMixin, ResourceBaseUpdateView):
    """
    Update a style
    """

    form_class = UpdateForm

    def form_valid(self, form):
        """
        Update the style type according to the style XML file.
        """

        obj = form.save(commit=False)
        xml_parse = read_xml_style(obj.file)
        if xml_parse:
            obj.style_type = StyleType.objects.filter(
                symbol_type=xml_parse["type"]
            ).first()
        obj.require_action = False
        obj.save()
        # Without this next line the tags won't be saved.
        form.save_m2m()
        resource_notify(obj, created=False, resource_type=self.resource_name)
        msg = _("The Style has been successfully updated.")
        messages.success(self.request, msg, "success", fail_silently=True)
        return HttpResponseRedirect(reverse_lazy("style_detail", kwargs={"pk": obj.id}))


class StyleListView(ResourceMixin, ResourceBaseListView):
    """Style ListView."""

class StyleByTagView(StyleListView):
    """Display StyleListView filtered on style tag"""

    def get_filtered_queryset(self, qs):
        response = qs.filter(tagged_items__tag__slug=unquote(self.kwargs["style_tag"]))
        return response

    def get_queryset(self):
        qs = super().get_queryset()
        return self.get_filtered_queryset(qs)

    def get_context_data(self, **kwargs):
        context = super(StyleByTagView, self).get_context_data(**kwargs)
        context.update(
            {
                "title": _("Style tagged with: %s") % unquote(self.kwargs["style_tag"]),
                "page_title": _("Tag: %s") % unquote(self.kwargs["style_tag"])
            }
        )
        return context

class StyleByTypeListView(StyleListView):
    """Display StyleListView filtered on style type"""

    def get_queryset(self):
        qs = super().get_queryset()
        style_type = self.kwargs["style_type"]
        return qs.filter(style_type__name=style_type)

    def get_context_data(self, **kwargs):
        """
        Override get_context_data.

        Add 'title' to be displayed as page title
        """

        context = super(StyleByTypeListView, self).get_context_data(**kwargs)
        context["title"] = "%s Styles" % (self.kwargs["style_type"],)
        return context


class StyleUnapprovedListView(ResourceMixin, ResourceBaseUnapprovedListView):
    """Unapproved Style ListView."""


class StyleRequireActionListView(ResourceMixin, ResourceBaseRequireActionListView):
    """Style requires action."""


class StyleDeleteView(ResourceMixin, ResourceBaseDeleteView):
    """Delete a style."""


class StyleReviewView(ResourceMixin, ResourceBaseReviewView):
    """Create a review"""


class StyleDownloadView(ResourceMixin, ResourceBaseDownload):
    """Download a style"""


def style_nav_content(request):
    model = ResourceMixin.model
    response = resource_nav_content(request, model)
    return response


@never_cache
def style_type_list(request):
    media_path = getattr(settings, "MEDIA_URL")
    qs = StyleType.objects.all()
    qs_json = serializers.serialize("json", qs)
    qs_load = json.loads(qs_json)
    qs_add = {"qs": qs_load, "icon_url": media_path}
    qs_json = json.dumps(qs_add)
    return HttpResponse(qs_json, content_type="application/json")

qgis-app/styles/templates/styles/form_snippet.html
{% load i18n %}
    <fieldset>
{% for field in form %}
        <div class="fieldWrapper {{ field.css_classes }}">
            {{ field.label_tag }}
            {% if field.errors %}
            <div class="alert alert-error">
            {{ field.errors }}
            </div>
            {% endif %}
            {{ field }}
            <div class="help">{{ field.help_text }}</div>
        </div>
{% endfor %}
    </fieldset>

qgis-app/styles/templates/styles/st_base.html
{% extends BASE_TEMPLATE %}{% load i18n %}

{% block app_title %}
<a href="/" class="logo">{% trans "Quantum GIS Style Repository" %}</a>
{% endblock %}


{% block menu %}
{{ block.super }}
{% endblock %}

qgis-app/styles/templates/styles/st_index.html
{% extends 'styles/st_base.html' %}
{% block content %}
<h3>QGIS Style Repository</h3>
<p>QGIS Style Repository is a place where styles of the layers in QGIS can be shared. The styles canbe Exported through the "Save Style" button in the Properties dialog, Style tab and can be Imported using the "Load Style" button.</p>

<h3>Browse and Download Styles <a href="list/" >HERE</a></h3>

<h3>Upload</h3>
<p>To upload a new style go to <a href="/styles/add/">Style Upload Form</a> and upload the <strong>.qml</strong> file exported by the "Save Style" option.</p>

{% endblock %}

qgis-app/styles/templates/styles/st_upload.html
{% extends 'styles/st_base.html' %}
{% block content %}
<h3>Style Upload Form</h3>
<p>The style upload form lets you upload the layer styles exported from QGIS into the online repository, which can be accessed by anyone. Kindly choose the <strong>.qml</strong> file exported by the "Save Style" option (Layer Properties dialog, Style tab) in QGIS 2.0 or later and add relevant tags so that it can be easily searched and retrieved by users.</p>
<form action="/styles/add/" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="id_name">Style Name: </label>
        {{ form.name }}
    </div>
    <div class="fieldWrapper">
        {{ form.xmlfile.errors }}
        <label for="id_xmlfile">Style QML File: </label>
        {{ form.xmlfile }}
    </div>
    <div class="fieldWrapper">
        {{ form.desc.errors }}
        <label for="id_desc">Description: </label>
        {{ form.desc }}
    </div>
    <div class"filedWrapper">
        {{ form.tags.errors }}
        <label for="id_tags">Tags (seperated by commas): </label>
        {{ form.tags }}
    </div>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

qgis-app/styles/templates/styles/style_base.html
{% extends BASE_TEMPLATE %}{% load i18n static thumbnail %}
{% block extratitle %}{% trans "Style"%}{% endblock %}
{% block app_title %}
<h2 xmlns="http://www.w3.org/1999/html">{% trans "QGIS Style"%}</h2>
{% endblock %}

{% block extrajs %}
    <style>
        div.style-polaroid{
            width: 100%;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            text-align: center;
            margin-top: 23px;
        }
        div.style-polaroid, div.span12.license {
            margin-left: 1em;
        }
        .style-title {
            margin-bottom: 0;
            padding-bottom: 0;
        }
    </style>
{% endblock %}

{% block menu %}
{{ block.super }}
<a class="btn btn-block btn-primary btn-large" href="{% url "style_create" %}"><i class="icon-upload icon-white icon-2x" style=" vertical-align: middle;"></i> {% trans "Upload Style" %}</a>
<h3>{% trans "Styles" %}</h3>
<ul class="nav nav-list">
    <li><a href="{% url 'style_list' %}">{% trans "Approved" %} <sup><span class="badge badge-info" id="all"></span></sup></a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'style_unapproved' %}">{% trans "Waiting Review" %} <sup><span class="badge badge-info" id="waiting_review"></span></sup></a></li>
        <li><a href="{% url 'style_require_action' %}">{% trans "Requiring Update" %} <sup><span class="badge badge-info" id="requiring_action"></span></sup></a></li>
        {% endif %}
</ul>

<div class="module_menu">
    <h3>{% trans "Style Type" %}</h3>
    <ul class="nav nav-list" id="styleList"></ul>

</div>
    <script type="text/javascript">
        $(document).ready(function(){
            $.ajax({
                type: 'GET',
                url: "{% url 'style_nav_content' %}",
                success: function (response){
                    if(response.waiting_review){$("#waiting_review").text(response.waiting_review)};
                    if(response.require_action){$("#requiring_action").text(response.require_action)};
                }
            })
            $.ajax({
                type: 'GET',
                url: "{% url 'style_nav_typelist' %}",
                success: function (response){
                    let icon_url = response.icon_url;
                    $.each(response.qs, function(i, val){
                        let name = val.fields.name
                        let icon = val.fields.icon
                        if(icon){
                            $("#styleList").append('<li><a href="/styles/types/' + name + '/"><img src="'+ icon_url+ icon +'" width="12" height="12">&nbsp;' + name + '</li>');
                        } else {
                            $("#styleList").append('<li><a href="/styles/types/' + name + '/">' + name + '</li>');
                        }
                    })
                }
            })

            // edit search input from base template, in order to use it for styles
            $("form.navbar-search").attr("action", "/styles/");
            })
    </script>
    
{% endblock %}

{% block "credits" %}
{% trans "This web application was developed by:" %}&nbsp;<a href="https://www.itopen.it">Alessandro Pasotti</a> and &nbsp;<a href="https://kartoza.com"><img src="{% static 'images/kartoza-logo-only.png' %}" alt="Kartoza icon" width="16" height="16">Kartoza</a>.
{% endblock %}

qgis-app/styles/templates/styles/style_confirm_delete.html
{% extends 'styles/style_base.html' %}{% load i18n %}
{% block content %}
    <h2>{% trans "Delete Style"%}: {{ style.name }}</h2>
    <form action="" method="post">{% csrf_token %}
        <p class="alert alert-danger">{% trans "Are you sure you want to permanently remove this style?"%}</p>
        <p><input type="submit" class="btn btn-danger" name="delete_confirm" value="{% trans "Delete" %}" /> <a class="btn btn-primary" href="{% url 'style_list' %}">{% trans "Cancel" %}</a></p>
    </form>

{% endblock %}

qgis-app/styles/templates/styles/style_detail.html
{% extends 'styles/style_base.html' %}{% load i18n static thumbnail %}

{% block content %}
        <h3 class="style-title">{{ style_detail.name|title }}</h3>
        {% if user == style_detail.creator or user.is_staff %}
        <div class="row pull-right">
            <a class="btn btn-primary btn-mini" href="{% url 'style_update' style_detail.id %}" title="{% trans "Edit" %}"><i class="icon-pencil icon-white"></i></a>&nbsp
            <a class="btn btn-danger btn-mini" href="{% url 'style_delete' style_detail.id %}" title="{% trans "Delete" %}"><i class="icon-remove icon-white"></i></a>&nbsp
        </div>
        {% endif %}
        <hr />
        <div class="row">
            <div class="span4 mb-5">
                <div class="style-polaroid">
                    {% thumbnail style_detail.thumbnail_image "420x420" format="PNG" as im %}
                    <img class="" alt="{% trans "Style icon" %}" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}" />
                    {% endthumbnail %}

                </div>

            </div>
            <div class="span8">
                <dl class="dl-horizontal">
                    <dd></dd>
                    <dt>Name</dt>
                    <dd>{{ style_detail.name }}</dd>
                    <dt>Description</dt>
                    <dd>{{ style_detail.description }}</dd>
                    <dt>Uploaded Date</dt>
                    <dd>{{ style_detail.upload_date|date:"d F Y" }}</dd>
                    <dt>Approved Date</dt>
                    <dd>{{ style_detail.stylereview_set.last.review_date|date:"d F Y"}}</dd>
                    <dt>Creator</dt>
                    <dd>{{ style_detail.get_creator_name|title }}</dd>
                    <dt>Type</dt>
                    <dd>
                        {{ style_detail.style_type.name }}
                    </dd>

                    <dt>Style File</dt>
                    <dd>
                        <div>
                             <a class="btn btn-primary btn-mini" href="{% url 'style_download' style_detail.id %}" title="{% trans "Download" %}"><i class="icon-download-alt"></i> Download</a>
                        </div>
                    </dd>
                </dl>

            </div>
            <div class="span12 license">
              <div class="media" style="margin-top: 2rem">
                <a class="pull-left" href="#">
                  <img src="{% static 'images/cc-zero.svg' %}">
                </a>
                <div class="media-body">
                  <p>This Style is made available under the <a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank">CC-0 license</a>.</p>
                </div>
              </div>
            </div>


        </div>
{% endblock %}

qgis-app/styles/templates/styles/style_form.html
{% extends "styles/style_base.html" %}{% load i18n static%}
{% block content %}
    <h2>{% trans "Upload Style" %}</h2>
    <p class="help">{% trans "To upload a new style, you can specify the xml file in this form." %}</p>

    {% if form.non_field_errors %}
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {% for error in form.non_field_errors %}
            <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include "styles/form_snippet.html" %}

        <div class="license-agreement">
            <label class="checkbox">
                <input type="checkbox" required> I confirm that I own these materials and have the rights to share them, including any embedded content, under the <a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank">CC-0 license</a>.
            </label>
        </div>

        <button class="btn btn-primary" id="licenseAgreed" type="submit">{% trans "Upload" %}</button>
    </form>

    <script type="text/javascript" src="{% static 'js/resource_upload.js' %}"></script>

{% endblock %}

qgis-app/styles/templates/styles/style_permission_deny.html
{% extends 'styles/style_base.html' %}{% load i18n %}
{% block content %}
    <h4 class="text-error">{% trans "Permission Denied"%}</h4>
    <p>{% trans context %}: {{ style_name }}.</p>
    <p><a class="btn btn-primary" href="{% url 'style_list' %}">{% trans "Back" %}</a></p>
{% endblock %}

qgis-app/styles/templates/styles/style_update_form.html
{% extends "styles/style_base.html" %}{% load i18n %}
{% block content %}
    <h2>{% trans "Update Style:" %} {{ style.name }}</h2>
    <p class="help">{% trans "To update your style, you can change the value in the input field." %}</p>

    {% if form.non_field_errors %}
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {% for error in form.non_field_errors %}
            <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include "styles/form_snippet.html" %}
        <button class="btn btn-primary" type="submit">{% trans "Update" %}</button>
    </form>

{% endblock %}